#!/usr/bin/perl -w

# Grabbed from
#	http://www.builderau.com.au/program/web/soa/Generate_stronger_random_passwords_with_Perl/0,39024632,39213084,00.htm

use strict;

use String::MkPasswd qw(mkpasswd);

#print "Passwords with mkpasswd.\n";
#print "Length 20 password: ",
#mkpasswd(-length => 20,
#-minnum => 4,
#-minlower => 4,
#-minupper => 2,
#-minspecial => 3),
#"\n";
#print "Length 13 password: ",
#mkpasswd(-length => 13,
#-minnum => 4,
#-minlower => 4,
#-minupper => 2,
#-minspecial => 3),
#"\n";

#print "Length 9 password: ", mkpasswd(), "\n";

#print "\n\nPassword with RandPasswd\n";

use Crypt::RandPasswd;

my $word = Crypt::RandPasswd->word(4, 6);
print "", $word, "\n";
